mixed-port: 7890
redir-port: 7892
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: :9999
external-ui: ui
secret: 
tun: {enable: true, stack: system}
experimental: {ignore-resolve-fail: true, interface-name: en0}
dns: {enable: true, ipv6: true, listen: 0.0.0.0:1053, use-hosts: true, enhanced-mode: redir-host, nameserver: [127.0.0.1], fallback: [127.0.0.1], fallback-filter: {geoip: true}}
store-selected: true
#ç”¨äºç¼–å†™è‡ªå®šä¹‰è®¾å®š(å¯å‚è€ƒhttps://lancellc.gitbook.io/clash)ï¼Œä¾‹å¦‚
#port: 7890
#hosts:
#   '*.clash.dev': 127.0.0.1 
#   'alpha.clash.dev': ::1
proxies:
proxy-groups:
  - name: Selection
    type: select
    proxies:
      - ğŸŒDirect
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
  - name: Daily
    type: select
    proxies:
      - ğŸŒDirect
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
  - name: Netflix
    type: select
    proxies:
      - ğŸŒDirect
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
  - name: Disney+
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
      - ğŸ‡¸ğŸ‡¬ [SSR]DisneyPlus
      - ğŸ‡¸ğŸ‡¬ [SS]WebHorizon
  - name: HBOMax
    type: select
    proxies:
      - ğŸ‡ªğŸ‡¸ [VMESS]HBOMax
  - name: Singapore
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
  - name: China
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
  - name: Speedtest
    type: select
    proxies:
      - ğŸŒDirect
      - ğŸ‡¸ğŸ‡¬ [VMESS]Amazon
      - ğŸ‡¸ğŸ‡¬ [SSR]DisneyPlus
  - name: ğŸ›¡Guard
    type: select
    proxies:
      - â›”ï¸Reject
      - ğŸŒDirect
  - name: ğŸŒDirect
    type: select
    proxies:
      - DIRECT
  - name: â›”ï¸Reject
    type: select
    proxies:
      - REJECT
rules:
 - DOMAIN-KEYWORD,adservice,ğŸ›¡Guard
 - DOMAIN,ad.51wnl-cq.com,ğŸ›¡Guard
 - DOMAIN,adextra.51wnl-cq.com,ğŸ›¡Guard
 - DOMAIN,log.51wnl-cq.com,ğŸ›¡Guard
 - DOMAIN,r.51wnl-cq.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iadsdk.apple.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.internal.unity3d.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.prd.ie.internal.unity3d.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,unityads.unity3d.com,ğŸ›¡Guard
 - DOMAIN,tunion-api.m.taobao.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,atm.youku.com,ğŸ›¡Guard
 - DOMAIN,ad.mobile.youku.com,ğŸ›¡Guard
 - DOMAIN,iyes.youku.com,ğŸ›¡Guard
 - DOMAIN,pl.cp31.ott.cibntv.net,ğŸ›¡Guard
 - DOMAIN,optimus-ads.amap.com,ğŸ›¡Guard
 - DOMAIN,optimus-ads.amap.com.w.alikunlun.com,ğŸ›¡Guard
 - DOMAIN,adproxy.autohome.com.cn,ğŸ›¡Guard
 - DOMAIN,rd.autohome.com.cn,ğŸ›¡Guard
 - DOMAIN,al.autohome.com.cn,ğŸ›¡Guard
 - DOMAIN,applogapi.autohome.com.cn,ğŸ›¡Guard
 - DOMAIN,adm0.autoimg.cn,ğŸ›¡Guard
 - DOMAIN,adm1.autoimg.cn,ğŸ›¡Guard
 - DOMAIN,adm2.autoimg.cn,ğŸ›¡Guard
 - DOMAIN,adm3.autoimg.cn,ğŸ›¡Guard
 - DOMAIN-SUFFIX,duapps.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,cpro.baidu.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,pos.baidu.com,ğŸ›¡Guard
 - DOMAIN,afd.baidu.com,ğŸ›¡Guard
 - DOMAIN,als.baidu.com,ğŸ›¡Guard
 - DOMAIN,duclick.baidu.com,ğŸ›¡Guard
 - DOMAIN,mobads.baidu.com,ğŸ›¡Guard
 - DOMAIN,mobads-logs.baidu.com,ğŸ›¡Guard
 - DOMAIN,nadvideo2.baidu.com,ğŸ›¡Guard
 - DOMAIN,nsclick.baidu.com,ğŸ›¡Guard
 - DOMAIN,t7z.cupid.iqiyi.com,ğŸ›¡Guard
 - DOMAIN,t7z.cupid.ptqy.gitv.tv,ğŸ›¡Guard
 - IP-CIDR,101.227.97.240/32,ğŸ›¡Guard,no-resolve
 - IP-CIDR,101.227.200.11/32,ğŸ›¡Guard,no-resolve
 - IP-CIDR,101.227.200.28/32,ğŸ›¡Guard,no-resolve
 - IP-CIDR,124.192.153.42/32,ğŸ›¡Guard,no-resolve
 - DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,ğŸ›¡Guard
 - DOMAIN,ad.toutiao.com,ğŸ›¡Guard
 - DOMAIN,pangolin.snssdk.com,ğŸ›¡Guard
 - DOMAIN,advertise.baicizhan.com,ğŸ›¡Guard
 - DOMAIN,advertise.baicizhan.org,ğŸ›¡Guard
 - DOMAIN,adx.yiche.com,ğŸ›¡Guard
 - DOMAIN,log.ycapp.yiche.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad.appboy.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-03.appboy.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-01.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-02.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-03.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-04.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-05.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-06.braze.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,iad-08.braze.com,ğŸ›¡Guard
 - DOMAIN,galaxy.bjcathay.com,ğŸ›¡Guard
 - DOMAIN,mdrecv.app.cntvwb.cn,ğŸ›¡Guard
 - DOMAIN,sdapprecv.app.cntvwb.cn,ğŸ›¡Guard
 - DOMAIN,vdapprecv.app.cntvwb.cn,ğŸ›¡Guard
 - DOMAIN,ad.21cn.com,ğŸ›¡Guard
 - DOMAIN,ad.k.21cn.com,ğŸ›¡Guard
 - DOMAIN,admarket.21cn.com,ğŸ›¡Guard
 - DOMAIN,adshows.21cn.com,ğŸ›¡Guard
 - DOMAIN,atrace.chelaile.net.cn,ğŸ›¡Guard
 - DOMAIN,logs.chelaile.net.cn,ğŸ›¡Guard
 - DOMAIN,dispatcher.360in.com,ğŸ›¡Guard
 - DOMAIN,ad.360in.com,ğŸ›¡Guard
 - DOMAIN,exp.360in.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,doubleclick.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,googleadservices.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,googleadsserving.cn,ğŸ›¡Guard
 - DOMAIN-SUFFIX,googlesyndication.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,googletagservices.com,ğŸ›¡Guard
 - DOMAIN,ads.youtube.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,da.mgtv.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,da.hunantv.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,log.hunantv.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,v2.hunantv.com,ğŸ›¡Guard
 - DOMAIN,adx.hupu.com,ğŸ›¡Guard
 - DOMAIN,adx-api.hupu.com,ğŸ›¡Guard
 - DOMAIN,goblin.hupu.com,ğŸ›¡Guard
 - DOMAIN,ad.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,adc.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,adcdn.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,adeng.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,pin.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,rp.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,rpt.hpplay.cn,ğŸ›¡Guard
 - DOMAIN,richmanapi.jxedt.com,ğŸ›¡Guard
 - DOMAIN,richmanmain.jxedt.com,ğŸ›¡Guard
 - DOMAIN,richmanrules.jxedt.com,ğŸ›¡Guard
 - DOMAIN,ad-stat.ksosoft.com,ğŸ›¡Guard
 - DOMAIN,img.auction-ads.wpscdn.cn,ğŸ›¡Guard
 - DOMAIN,counter.kingsoft.com,ğŸ›¡Guard
 - DOMAIN,counter.ksosoft.com,ğŸ›¡Guard
 - DOMAIN,minfo.wps.cn,ğŸ›¡Guard
 - DOMAIN,mobad.ijinshan.com,ğŸ›¡Guard
 - DOMAIN,ups.ksmobile.net,ğŸ›¡Guard
 - DOMAIN,ws.ksmobile.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,e.kuaishou.com,ğŸ›¡Guard
 - DOMAIN,js-ad.a.yximgs.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,webp2p.letv.com,ğŸ›¡Guard
 - DOMAIN,ark.letv.com,ğŸ›¡Guard
 - DOMAIN,emma-414870e223.huodonghezi.com,ğŸ›¡Guard
 - DOMAIN,g3.letv.com,ğŸ›¡Guard
 - DOMAIN,n.mark.letv.com,ğŸ›¡Guard
 - DOMAIN,a.wkanx.com,ğŸ›¡Guard
 - DOMAIN,cwx.lianwangtech.com,ğŸ›¡Guard
 - DOMAIN,c1wx.lianwangtech.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.msn.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads1.msn.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads2.msn.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,rads.msn.com,ğŸ›¡Guard
 - DOMAIN,mobileads.msn.com,ğŸ›¡Guard
 - DOMAIN,ad.api.moji.com,ğŸ›¡Guard
 - DOMAIN,adlaunch.moji.com,ğŸ›¡Guard
 - DOMAIN,ads.mojicdn.com,ğŸ›¡Guard
 - DOMAIN,v1.log.moji.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,dsp.youdao.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,union.youdao.com,ğŸ›¡Guard
 - DOMAIN,ad.bn.netease.com,ğŸ›¡Guard
 - DOMAIN,ad.yixin.im,ğŸ›¡Guard
 - DOMAIN,admusicpic.music.126.net,ğŸ›¡Guard
 - DOMAIN,gorgon.youdao.com,ğŸ›¡Guard
 - DOMAIN,iad.g.163.com,ğŸ›¡Guard
 - DOMAIN,iadmat.nosdn.127.net,ğŸ›¡Guard
 - DOMAIN,iadmusicmat.music.126.net,ğŸ›¡Guard
 - DOMAIN,iadmusicmatvideo.music.126.net,ğŸ›¡Guard
 - DOMAIN,impservice.dictapp.youdao.com,ğŸ›¡Guard
 - DOMAIN,impservice.youdao.com,ğŸ›¡Guard
 - DOMAIN,n.3g.163.com,ğŸ›¡Guard
 - DOMAIN,nex.163.com,ğŸ›¡Guard
 - DOMAIN,yt-adp.nosdn.127.net,ğŸ›¡Guard
 - DOMAIN,yt-adp.ws.126.net,ğŸ›¡Guard
 - DOMAIN,ads.aplus.pptv.com,ğŸ›¡Guard
 - DOMAIN,ads.aplusapi.pptv.com,ğŸ›¡Guard
 - DOMAIN,asimgs.pplive.cn,ğŸ›¡Guard
 - DOMAIN,de.as.pptv.com,ğŸ›¡Guard
 - DOMAIN,regist.fotoable.com,ğŸ›¡Guard
 - DOMAIN,cdn.adapi.fotoable.com,ğŸ›¡Guard
 - DOMAIN,adnew.wifi8.com,ğŸ›¡Guard
 - DOMAIN,adfile.wifi8.com,ğŸ›¡Guard
 - DOMAIN,ad-analysis.pconline.com.cn,ğŸ›¡Guard
 - DOMAIN,iad0ssl.pcauto.com.cn,ğŸ›¡Guard
 - DOMAIN,iad0ssl.pconline.com.cn,ğŸ›¡Guard
 - DOMAIN,imgad0.pcauto.com.cn,ğŸ›¡Guard
 - DOMAIN,imgad0.pconline.com.cn,ğŸ›¡Guard
 - DOMAIN,ivy.pchouse.com.cn,ğŸ›¡Guard
 - DOMAIN-SUFFIX,deliver.ifeng.com,ğŸ›¡Guard
 - DOMAIN,api.newad.ifeng.com,ğŸ›¡Guard
 - DOMAIN,ifengad.3g.ifeng.com,ğŸ›¡Guard
 - DOMAIN,ad.qingting.fm,ğŸ›¡Guard
 - DOMAIN,adlaunch.qingting.fm,ğŸ›¡Guard
 - DOMAIN,ad-cdn.qingting.fm,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.oppomobile.com,ğŸ›¡Guard
 - DOMAIN,adsfs.oppomobile.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,alitui.weibo.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,beacon.sina.com.cn,ğŸ›¡Guard
 - DOMAIN,adimg.uve.weibo.com,ğŸ›¡Guard
 - DOMAIN,adimg.vue.weibo.com,ğŸ›¡Guard
 - DOMAIN,u1.img.mobile.sina.cn,ğŸ›¡Guard
 - DOMAIN,sax.sina.com.cn,ğŸ›¡Guard
 - DOMAIN,saxs.sina.com.cn,ğŸ›¡Guard
 - DOMAIN,saxn.sina.com.cn,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ad.sohu.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.sohu.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,aty.sohu.com,ğŸ›¡Guard
 - DOMAIN,imp.optaim.com,ğŸ›¡Guard
 - DOMAIN,v2.reachmax.cn,ğŸ›¡Guard
 - DOMAIN,hui.sohu.com,ğŸ›¡Guard
 - DOMAIN,ads.snapchat.com,ğŸ›¡Guard
 - DOMAIN,adsapi.snapchat.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,e.qq.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,gdt.qq.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,l.qq.com,ğŸ›¡Guard
 - DOMAIN,adsmind.apdcdn.tc.qq.com,ğŸ›¡Guard
 - DOMAIN,adsmind.gdtimg.com,ğŸ›¡Guard
 - DOMAIN,adsmind.tc.qq.com,ğŸ›¡Guard
 - DOMAIN,pgdt.gtimg.cn,ğŸ›¡Guard
 - DOMAIN,pgdt.gtimg.com,ğŸ›¡Guard
 - DOMAIN,pgdt.ugdtimg.com,ğŸ›¡Guard
 - DOMAIN,splashqqlive.gtimg.com,ğŸ›¡Guard
 - DOMAIN,wa.gtimg.com,ğŸ›¡Guard
 - DOMAIN,wxsnsdy.wxs.qq.com,ğŸ›¡Guard
 - DOMAIN,wxsnsdythumb.wxs.qq.com,ğŸ›¡Guard
 - DOMAIN,ad.tencentmusic.com,ğŸ›¡Guard
 - DOMAIN,adserviceretry.kugou.com,ğŸ›¡Guard
 - DOMAIN,ads.service.kugou.com,ğŸ›¡Guard
 - DOMAIN,adsfile.bssdlbig.kugou.com,ğŸ›¡Guard
 - DOMAIN,g.koowo.com,ğŸ›¡Guard
 - DOMAIN,kgmobilestat.kugou.com,ğŸ›¡Guard
 - DOMAIN,kgmobilestatbak.kugou.com,ğŸ›¡Guard
 - DOMAIN,mobilelog.kugou.com,ğŸ›¡Guard
 - DOMAIN,mobilead.kuwo.cn,ğŸ›¡Guard
 - DOMAIN,rich.kuwo.cn,ğŸ›¡Guard
 - DOMAIN,adm.10jqka.com.cn,ğŸ›¡Guard
 - DOMAIN,stat.10jqka.com.cn,ğŸ›¡Guard
 - DOMAIN,admonitor.thepaper.cn,ğŸ›¡Guard
 - DOMAIN,adpai.thepaper.cn,ğŸ›¡Guard
 - DOMAIN,imgadpai.thepaper.cn,ğŸ›¡Guard
 - DOMAIN,adsp.xunlei.com,ğŸ›¡Guard
 - DOMAIN,etl.xlmc.sandai.net,ğŸ›¡Guard
 - DOMAIN,adv-adlog.variflight.com,ğŸ›¡Guard
 - DOMAIN,adv-ads.variflight.com,ğŸ›¡Guard
 - DOMAIN,app-ad.variflight.com,ğŸ›¡Guard
 - DOMAIN,adlog.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,adreq.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,ads-marketing-vivofs.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,adsdk.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,adsstatic.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,adxlog.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN,vcardsdkservice.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN-KEYWORD,stsdk.vivo.com.cn,ğŸ›¡Guard
 - DOMAIN-KEYWORD,stsdk.vivoglobal.com,ğŸ›¡Guard
 - DOMAIN,ads.viber.com,ğŸ›¡Guard
 - DOMAIN,ads-d.viber.com,ğŸ›¡Guard
 - DOMAIN,ads.aws.viber.com,ğŸ›¡Guard
 - DOMAIN,ad.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adbs.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adse.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adse.wsa.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adbehavior.wsa.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adbehavior.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,adsebs.ximalaya.com,ğŸ›¡Guard
 - DOMAIN,ads-img-qc.xhscdn.com,ğŸ›¡Guard
 - DOMAIN,ads-video-al.xhscdn.com,ğŸ›¡Guard
 - DOMAIN,ads-video-qc.xhscdn.com,ğŸ›¡Guard
 - DOMAIN,t-ads.xiaohongshu.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,adserver.yahoo.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,adspecs.yahoo.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,advertising.yahoo.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,gemini.yahoo.com,ğŸ›¡Guard
 - DOMAIN,admarketing.yahoo.net,ğŸ›¡Guard
 - DOMAIN,ads.auctions.yahoo.com,ğŸ›¡Guard
 - DOMAIN,ads.finance.yahoo.com,ğŸ›¡Guard
 - DOMAIN,ads.yahoo.com,ğŸ›¡Guard
 - DOMAIN,ads.yahoo.de,ğŸ›¡Guard
 - DOMAIN,appcloud2.in.zhihu.com,ğŸ›¡Guard
 - DOMAIN,mqtt.zhihu.com,ğŸ›¡Guard
 - DOMAIN,sugar.zhihu.com,ğŸ›¡Guard
 - DOMAIN,118.89.204.198,ğŸ›¡Guard
 - IP-CIDR,118.89.204.198/32,ğŸ›¡Guard,no-resolve
 - IP-CIDR6,2402:4e00:1200:ed00:0:9089:6dac:96b6/128,ğŸ›¡Guard,no-resolve
 - DOMAIN,apppv.zol.com.cn,ğŸ›¡Guard
 - DOMAIN,pvnapp.zol.com.cn,ğŸ›¡Guard
 - DOMAIN-SUFFIX,adjust.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,airpr.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,cr-nielsen.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,hotjar.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,hotjar.io,ğŸ›¡Guard
 - DOMAIN-SUFFIX,hs-analytics.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,kissmetrics.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,kochava.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,liadm.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,marketo.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,mobileapptracking.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,mparticle.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,nexac.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,nr-data.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,pardot.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,parrable.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,petametrics.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,predic.io,ğŸ›¡Guard
 - DOMAIN-SUFFIX,quantcount.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,quantserve.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,richmetrics.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,rtbasia.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,scorecardresearch.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,seewhy.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,segment.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,segment.io,ğŸ›¡Guard
 - DOMAIN-SUFFIX,segmentify.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,sentiance.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,serverbid.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,sessionm.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,smartlook.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,socdm.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,socialannex.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,socialbakers.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,sociaplus.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,stathat.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,stats-locations.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tagcommander.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tailtarget.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tapad.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tapfiliate.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tapinfluence.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tapstream.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tend.io,ğŸ›¡Guard
 - DOMAIN-SUFFIX,trackingio.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,woopra.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,wootric.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,wowanalytics.co.uk,ğŸ›¡Guard
 - DOMAIN-SUFFIX,zoomanalytics.co,ğŸ›¡Guard
 - DOMAIN-SUFFIX,ads.linkedin.com,ğŸ›¡Guard
 - DOMAIN,analytics.slashdotmedia.com,ğŸ›¡Guard
 - DOMAIN,zgsdk.zhugeio.com,ğŸ›¡Guard
 - DOMAIN,js.users.51.la,ğŸ›¡Guard
 - DOMAIN,mc.51.la,ğŸ›¡Guard
 - DOMAIN,wc.51.la,ğŸ›¡Guard
 - DOMAIN,track.58.com,ğŸ›¡Guard
 - DOMAIN,tracklog.58.com,ğŸ›¡Guard
 - DOMAIN,hm.baidu.com,ğŸ›¡Guard
 - DOMAIN,hmma.baidu.com,ğŸ›¡Guard
 - DOMAIN,log.byteoversea.com,ğŸ›¡Guard
 - DOMAIN,log.tiktokv.com,ğŸ›¡Guard
 - DOMAIN,log-hl-ipv6.snssdk.com,ğŸ›¡Guard
 - DOMAIN,log-lq.snssdk.com,ğŸ›¡Guard
 - DOMAIN,log-va.tiktokv.com,ğŸ›¡Guard
 - DOMAIN,xlog.snssdk.com,ğŸ›¡Guard
 - DOMAIN,track.tiara.daum.net,ğŸ›¡Guard
 - DOMAIN,track.tiara.kakao.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,googletagmanager.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,google-analytics.com,ğŸ›¡Guard
 - DOMAIN,safebrowsing.googleapis.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,gozendata.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,gzads.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,gz-data.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,giocdn.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,growingio.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,tracking.miui.com,ğŸ›¡Guard
 - DOMAIN,data.mistat.xiaomi.com,ğŸ›¡Guard
 - DOMAIN,tracking.intl.miui.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,cpatrk.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,talkingdata.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,talkingdata.net,ğŸ›¡Guard
 - DOMAIN-SUFFIX,udrig.com,ğŸ›¡Guard
 - DOMAIN-SUFFIX,trace.qq.com,ğŸ›¡Guard
 - DOMAIN,btrace.qq.com,ğŸ›¡Guard
 - DOMAIN,btrace.video.qq.com,ğŸ›¡Guard
 - DOMAIN,mtrace.qq.com,ğŸ›¡Guard
 - DOMAIN,safebrowsing.urlsec.qq.com,ğŸ›¡Guard
 - DOMAIN,track.tenjin.com,ğŸ›¡Guard
 - DOMAIN,track.tenjin.io,ğŸ›¡Guard
 - DOMAIN-SUFFIX,acfun.cn,China
 - DOMAIN-SUFFIX,aixifan.com,China
 - DOMAIN-SUFFIX,biliapi.net,China
 - DOMAIN-SUFFIX,bilibili.com,China
 - DOMAIN-SUFFIX,bilivideo.com,China
 - DOMAIN-SUFFIX,hdslb.com,China
 - DOMAIN-SUFFIX,video.qq.com,China
 - DOMAIN-SUFFIX,i.qq.com,China
 - DOMAIN-SUFFIX,v.qq.com,China
 - DOMAIN-SUFFIX,iqiyi.com,China
 - DOMAIN-SUFFIX,71edge.com,China
 - DOMAIN-SUFFIX,soku.com,China
 - DOMAIN-SUFFIX,youku.com,China
 - DOMAIN-SUFFIX,ykimg.com,China
 - DOMAIN-SUFFIX,ixigua.com,China
 - DOMAIN-SUFFIX,snssdk.com,China
 - DOMAIN-SUFFIX,hitv.com,China
 - DOMAIN-SUFFIX,hunantv.com,China
 - DOMAIN-SUFFIX,mgtv.com,China
 - DOMAIN-SUFFIX,le.com,China
 - DOMAIN-SUFFIX,pplive.cn,China
 - DOMAIN-SUFFIX,pptv.com,China
 - DOMAIN-SUFFIX,itc.cn,China
 - DOMAIN-SUFFIX,sohu.com,China
 - DOMAIN-SUFFIX,cmvideo.cn,China
 - DOMAIN-SUFFIX,miguvideo.com,China
 - DOMAIN-SUFFIX,music.qq.com,China
 - DOMAIN-SUFFIX,music.tc.qq.com,China
 - DOMAIN-SUFFIX,qqmusic.qq.com,China
 - DOMAIN-SUFFIX,tencentmusic.com,China
 - DOMAIN-SUFFIX,y.qq.com,China
 - DOMAIN,aqqmusic.tc.qq.com,China
 - DOMAIN,moo.qq.com,China
 - DOMAIN-SUFFIX,kuwo.cn,China
 - DOMAIN-SUFFIX,kugou.com,China
 - DOMAIN-SUFFIX,music.163.com,China
 - DOMAIN-SUFFIX,music.126.net,China
 - DOMAIN,mam.netease.com,China
 - DOMAIN,api.iplay.163.com,China
 - DOMAIN-SUFFIX,qianqian.com,China
 - DOMAIN-SUFFIX,taihe.com,China
 - DOMAIN-SUFFIX,migu.cn,China
 - DOMAIN-SUFFIX,ai.xiaomi.com,China
 - DOMAIN-SUFFIX,music.xiaomi.com,China
 - DOMAIN-SUFFIX,dmhmusic.com,China
 - DOMAIN-SUFFIX,koolshare.cn,China
 - DOMAIN-SUFFIX,tongdun.net,China
 - DOMAIN-SUFFIX,right.com.cn,China
 - DOMAIN-SUFFIX,qhres2.com,China
 - DOMAIN-SUFFIX,pstatp.com,China
 - DOMAIN-SUFFIX,toutiao.com,China
 - DOMAIN-SUFFIX,baidu.com,China
 - DOMAIN-SUFFIX,17jita.com,China
 - DOMAIN-SUFFIX,jitaba.cn,China
 - DOMAIN-SUFFIX,ccguitar.cn,China
 - DOMAIN-SUFFIX,echangwang.com,China
 - DOMAIN-SUFFIX,speedtest.net,Speedtest
 - DOMAIN-SUFFIX,tm.com.my,ğŸŒDirect
 - DOMAIN-SUFFIX,nflxvideo.net,Netflix
 - DOMAIN-SUFFIX,netflix.com,Netflix
 - DOMAIN-SUFFIX,fast.com,Netflix
 - DOMAIN-SUFFIX,google.com,Daily
 - DOMAIN-SUFFIX,facebook.com,Daily
 - DOMAIN-SUFFIX,fbcdn.net,Daily
 - DOMAIN-SUFFIX,messenger.com,Daily
 - DOMAIN-SUFFIX,youtube.com,Daily
 - DOMAIN-SUFFIX,instagram.com,Daily
 - DOMAIN-SUFFIX,disneyplus.com,Disney+
 - DOMAIN-SUFFIX,disney-plus.net,Disney+
 - DOMAIN-SUFFIX,dssott.com,Singapore
 - DOMAIN-SUFFIX,bamgrid.com,Disney+
 - DOMAIN-SUFFIX,optimizely.com,HBOMax
 - DOMAIN-SUFFIX,msedge.net,HBOMax
 - DOMAIN-SUFFIX,azureedge.net,HBOMax
 - DOMAIN-SUFFIX,hbomax.com,HBOMax
 - DOMAIN-SUFFIX,hbo.com,HBOMax
 - DOMAIN-SUFFIX,unifi.tv,ğŸŒDirect
 - DOMAIN-SUFFIX,astro.com.my,ğŸŒDirect
 - DOMAIN-SUFFIX,scdn.co,ğŸŒDirect
 - DOMAIN-SUFFIX,spotify.com,ğŸŒDirect
 - DOMAIN-SUFFIX,onesignal.com,ğŸŒDirect
 - DOMAIN-SUFFIX,local,ğŸŒDirect
 - SRC-IP-CIDR,1.9.58.117/32,ğŸŒDirect
 - IP-CIDR,192.168.0.0/16,ğŸŒDirect,no-resolve
 - IP-CIDR,10.0.0.0/8,ğŸŒDirect,no-resolve
 - IP-CIDR,172.16.0.0/12,ğŸŒDirect,no-resolve
 - IP-CIDR,127.0.0.0/8,ğŸŒDirect,no-resolve
 - IP-CIDR,100.64.0.0/10,ğŸŒDirect,no-resolve
 - IP-CIDR6,::1/128,ğŸŒDirect,no-resolve
 - IP-CIDR6,fc00::/7,ğŸŒDirect,no-resolve
 - IP-CIDR6,fe80::/10,ğŸŒDirect,no-resolve
 - IP-CIDR6,fd00::/8,ğŸŒDirect,no-resolve
 - GEOIP,CN,China
 - MATCH,Selection
